### ISSUE TITLE
Make content of `window-body` able to scroll

### ISSUE THREAD

**Issue by NaitLee** [botoxparty/XP.css#33]
I'm just making an explorer.exe liked thing, and need content of `window-body` to scroll (rather than overflow).
So I tried this CSS:
```css
.window-body {
    overflow: auto;
    height: calc(100% - 44px);  /* (inherit-height 100%) - (title-bar 21px) - (title-bar-border 1px) - (title-bar-padding 2 x 3px) - (window-body-margin 2 x 8px) */
}
```
Then it works as expected :)
